# Generated by Django 5.0.6 on 2024-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('shape', models.CharField(choices=[('SQUARE', 'Square'), ('CIRCLE', 'Circle'), ('TRIANGLE', 'Triangle')], default='SQUARE', max_length=10)),
            ],
        ),
    ]
