# Generated by Django 5.0.6 on 2024-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hddata',
            name='shape',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Circle'), (1, 'Point'), (2, 'Line'), (3, 'Triangle'), (4, 'Square')], default=0),
        ),
    ]
